### ISSUE TITLE
Support for experiments with only 1 channel at FMI

### ISSUE THREAD

**Issue by jluethi** [jluethi/fractal-faim-ipa#16]
Currently, the parser doesn't support single channel experiments.
See example data here: Users/maehmari/2_Experiments/002_002A1/MM-002-002A1-EH5A-1-1

Handle:
No wavelength specified
No  sites specified

(also, why does this not work with ZMB mode?)

**Comment by jluethi** [comment]
cc @mariusmaehlen

**Comment by jluethi** [comment]
I think this is still an issue and triggers errors like the following (reported by Clara):

```
Traceback (most recent call last):
  File "//FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.2.0/venv/lib/python3.9/site-packages/fractal_faim_hcs/create_ome_zarr_md.py", line 115, in <module>
    run_fractal_task(
  File "//FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.2.0/venv/lib64/python3.9/site-packages/fractal_tasks_core/tasks/_utils.py", line 79, in run_fractal_task
    metadata_update = task_function(**pars)
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "//FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.2.0/venv/lib/python3.9/site-packages/fractal_faim_hcs/create_ome_zarr_md.py", line 80, in create_ome_zarr_md
    build_zarr_scaffold(
  File "//FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.2.0/venv/lib64/python3.9/site-packages/faim_hcs/Zarr.py", line 142, in build_zarr_scaffold
    names = files["name"].unique()
  File "//FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.2.0/venv/lib64/python3.9/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "//FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.2.0/venv/lib64/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'name'
```

**Comment by jluethi** [comment]
Basically, the issue is that the parser returns an empty list of files. The call `parse_files(acquisition_dir)` returns an empty dataframe.
This is the case of for the current custom branch of faim-hcs, as well as the current main of the refactored faim-hcs (see https://github.com/fmi-faim/faim-hcs/commit/10790e53f72dce177a074c74034cd178c4e43606).

=> we'll need to create a minimal test set and have a look with the faim-hcs library and with FAIM.
